apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          #image: yuufnn/nfs-external-provisioner:v4.0.0
          image: base.image.docker:5000/k8s/nfs-client-provisioner:v4.0.0-k8s1.20.15
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 192.168.157.200
            - name: NFS_PATH
              value: /home/nfs/k8s
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.157.200
            path: /home/nfs/k8s
