---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: grafana
  name: grafana-svc
  namespace: prometheus
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: grafana