apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertmanager
  name: alertmanager-svc
  namespace: prometheus
spec:
  selector:
    app: alertmanager
  ports:
    - name: alert
      port: 9093
      targetPort: http
  sessionAffinity: None
  type: NodePort