apiVersion: v1
data:
  config.yml: |-
    global:
      smtp_smarthost: 'smtp.qq.com:465'
      smtp_from: '1140935517@qq.com'
      smtp_auth_username: '1140935517@qq.com'
      smtp_auth_password: 'scklssmvcjlhjbcj'
      smtp_require_tls: false

    route:
      group_by: ['alertname', 'cluster']
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 20m
      receiver: default
      routes:
      - receiver: email
        group_wait: 10s
        match:
          team: node
    receivers:
    - name: 'default'
      email_configs:
      - to: '1140935517@qq.com'
        send_resolved: true
    - name: 'email'
      email_configs:
      - to: '1140935517@qq.com'
        send_resolved: true
kind: ConfigMap
metadata:
  name: alert-config
  namespace: prometheus